### ISSUE TITLE
Can't get it to pair with my shock collars

### ISSUE THREAD

**Issue by giplgwm** [bdsm-spuddy/esp8266-shockduino#1]
I've uploaded the code successfully to my NodeMCU board, I did have to make a minor change to get it to actually load the html, adding <Include FS.h> and "SPIFFS.begin();" to the .ino. I uploaded the html files using "ESP8266 Sketch Data Upload" plugin on v1.8 of the arduino IDE. If this is incorrect please advise.

Now I have the html page working, but it will not pair with my collar after putting it into pairing mode. The collars I have are [here](https://www.amazon.com/5-150lbs-Flashing-Training-Adjustable-Vibration/dp/B0BWQT95JG/ref=sr_1_7?crid=X1DZVMVY97D6&dib=eyJ2IjoiMSJ9.rG7DOJT5j9mucPm48Wd1THdCZDGUvWqVh7wcGXc1BkMbNlF4j0gwfnewAl0SVbfd7soqYWRBc5vo7pWPfd6Z4AbgsO6C_5pjWFP847ktbgUAgNLHAD2c6N9kftG--Pc07YKYZQIiRGI8U9FBKO355r8YyKWsY9AHF1wFpfnuGxlbyjygHrnabIwMZI-qr8zBVmZ2whgQumLkYFaXaU_mQgEzGg5qEsfv4jpmwzxZlTOkwddiRMkMZ7afEw4SlF1umqxouTcxVBfphHJtW5-WuBCel-rFr_yL5Q6Twl5MGJs.5KYg91PHQjZ1bLGzHWuMvdFZVFMAUjyKFuFz18SR6Ow&dib_tag=se&keywords=shock+collars+2&qid=1714345728&sprefix=shock+collars+2+%2Caps%2C71&sr=8-7), I'm using the 433mhz transmitter modules linked in your README, and [this](https://www.amazon.com/5-150lbs-Flashing-Training-Adjustable-Vibration/dp/B0BWQT95JG/ref=sr_1_7?crid=X1DZVMVY97D6&dib=eyJ2IjoiMSJ9.rG7DOJT5j9mucPm48Wd1THdCZDGUvWqVh7wcGXc1BkMbNlF4j0gwfnewAl0SVbfd7soqYWRBc5vo7pWPfd6Z4AbgsO6C_5pjWFP847ktbgUAgNLHAD2c6N9kftG--Pc07YKYZQIiRGI8U9FBKO355r8YyKWsY9AHF1wFpfnuGxlbyjygHrnabIwMZI-qr8zBVmZ2whgQumLkYFaXaU_mQgEzGg5qEsfv4jpmwzxZlTOkwddiRMkMZ7afEw4SlF1umqxouTcxVBfphHJtW5-WuBCel-rFr_yL5Q6Twl5MGJs.5KYg91PHQjZ1bLGzHWuMvdFZVFMAUjyKFuFz18SR6Ow&dib_tag=se&keywords=shock+collars+2&qid=1714345728&sprefix=shock+collars+2+%2Caps%2C71&sr=8-7) NodeMCU board

The light on the NodeMCU flashes when i press "beep" to try pairing, but nothing happens on the collar side. I've tried swapping the Transmitter module 3 times, so i doubt they're all defective. The transmitter is wired - GRD - GRD, 3.3v - VCC, D0 - INPUT. Any advice here?

Thanks

**Comment by bdsm-spuddy** [comment]
You shouldn't need SPIFFS; the `html.h` file contains all the html as strings.  You should just be able to compile the ino file (which includes `html.h`) and so it's all in one blob.  No SPIFFS or other filesystem is needed.  If you change the html then you'll  need to run `gen_html` to create a new `html.h` (the `Makefile` has the necessary rules).

I do not know that model of collar, however it looks like it has "battery level indicators" which is sent from the collar back to the receiver.  So it's very very possible these collars use a different protocol to communicate and aren't compatible.

**Comment by giplgwm** [comment]
Can you link to a collar thats confirmed to work? Would be extremely helpful, thanks for the quick reply!

**Comment by bdsm-spuddy** [comment]
There's a link in the README to https://www.amazon.com/gp/product/B00W6ZHZMI which is the one I bought in 2015.  Not as fancy as the one you got but it works for me!
